---
- hosts: all

#
# Configure to match your environment
#
  vars:
    variable_host: 10.0.0.4
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://10.0.0.2:8443
      api_version: v5_0
    enterprise_name: Company XYZ
    enterprise_admin_username: ansible-admin
    nuage_dom_temp:
      id: 65dc31cb-163f-4cab-af60-0f6b8bbd14bb

  tasks:
  - name: Finding Enterprise
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Enterprise
      command: find
      properties:
        name: "{{ enterprise_name }}"
    register: nuage_enterprise

  # Creating a new Domain (if it doesn't exist yet)
  - name: Creating a few Domains from the DomainTemplate
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Domain
      parent_id: "{{ nuage_enterprise.id }}"
      parent_type: Enterprise
      state: present
      match_filter: "name == '{{ item }}'"
      properties:
        name: "{{ item }}"
        description: "Created by Ansible"
        template_id: "{{ nuage_dom_temp.id }}"
    with_items:
      - "Web Application AAA Instance"

  -  name: Create Openstack VSD-Managed Network
     command: neutron net-create testnet1 --os-username admin --os-password password --os-auth-url http://10.0.0.4:5000/v3 --os-project-name admin --os-user-domain-name Default --os-project-domain-name Default
     ignore_errors: yes

  -  name: Create Openstack VSD-Managed Subnet
     command: neutron subnet-create testnet1 192.168.3.0/24 --name testsubnet1 --nuagenet f2c5bedc-2c08-4865-a864-5530a7b47ab3 --net-partition 'Company XYZ' --os-username admin --os-password password --os-auth-url http://10.0.0.4:5000/v3 --os-project-name admin --os-user-domain-name Default --os-project-domain-name Default
     ignore_errors: yes
