---
- hosts: localhost

#
# Configure to match your environment
#
  vars:
    nuage_auth:
      api_username: csproot
      api_password: csproot
      api_enterprise: csp
      api_url: https://10.0.0.4:8443
      api_version: v5_0
    enterprise_name: Ansible-Test
    enterprise_new_name: Ansible-Updated-Test
    enterprise_admin_username: ansible-admin
    enterprise_admin_password: ansible
    enterprise_admin_new_password: ansible_new
    enterprise_admin_first_name: Ansible
    enterprise_admin_last_name: Admin
    enterprise_admin_email: ansible@localhost.local

  tasks:
  # Deleting an enterprise
  - name: Delete Enterprise
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Enterprise
      id: "{{ nuage_enterprise.id }}"
      state: absent
